### PR TITLE
colour tweak

### PR DESCRIPTION
**Pull request by arallsopp**
started tweaking those icons for you.

### CODE REVIEW

**Comment by Mariusthvdb** [comment]
check the keyword on Deathstar .... not perse a light ;-)

**Comment by Mariusthvdb** [comment]
ofcourse! ok no problem then ;-)
just that I had already set the color fill on those 2 so we now have a conflict..

**Comment by arallsopp** [comment]
Oh, yes, I see. We added it in different parts of the file. You can just go 'Resolve conflicts' and mark each as resolved.

**Comment by arallsopp** [comment]
Looking good. Well done.

**Pull request merged**
