### PR TITLE
Added:

### PR DESCRIPTION
**Pull request by yormedia**
Nordic wall light
Sunshade plane (open, closed)
Sunshade striped (open, closed)
Tuya color sphere desklight

### CODE REVIEW

**Comment by yormedia** [comment]
Sorry for the multiple commits..

**Comment by yormedia** [comment]
Changed the nordic light, was not happy with it.

**Comment by Mariusthvdb** [comment]
sunshades and nordic walls seem awfully thin, and not according to MDI specifications. could you have another look please?Aware we can do any icon here we like, but I feel we should adhere to the MDI specs as much as possible

**Comment by Mariusthvdb** [comment]
will you be fixing this?

id love to add the icons, but you should take out the google-home as that has already been merged by Andy

**Comment by Mariusthvdb** [comment]
closing because no response.
Please open a new PR when required

**Pull request closed without merging**
