### PR TITLE
Add recessed light groups

### PR DESCRIPTION
**Pull request by schmittyd**
Add recessed light groups for 2, 3 and 4 lights. Based on mdi:light-recessed single icon.

### CODE REVIEW

**Comment by Mariusthvdb** [comment]
thanks for your contribution!

you are aware this only adds these icons to the /svg folder? Meaning you can only use them with the custom_component. (I already stated that will be the way forward, use CC + svg folder, so I am fine with that)

You didnt add them in the .js resource file which is used in the frontend plugin.

Could you please indicate the source/editor of these files, and their authorization of course. We need correct attribution.

**Comment by schmittyd** [comment]
I couldn't figure out how to get the path information from the svg to add it to the js.

I used Affinity Designer. The icon sets are based on the single mdi:light-recessed icon.

I have already tried requesting them to be added, but they will not allow it.

**Comment by schmittyd** [comment]
How do I use custom_component?

**Comment by Mariusthvdb** [comment]
> How do I use custom_component?

just download it and add to your CC folder

Scherm­afbeelding 2024-07-29 om 17 38 43

next create a folder called `custom_icons` in /www, and drop any .svg icon you like in there

after a restart, you can use the icon picker in Home Assistant UI and look for cli: icons

Scherm­afbeelding 2024-07-29 om 17 40 47

**Comment by schmittyd** [comment]
Should I move custom-icons from www/community to custom_components?

**Comment by Mariusthvdb** [comment]
> Should I move custom-icons from www/community to custom_components?

No, that is the js plugin. that is a separate thing from the custom component you see in the custom_components folder

Scherm­afbeelding 2024-07-30 om 11 24 14

**Comment by schmittyd** [comment]
I don't know why. This is how they should appear.
light-recessed-group-2
light-recessed-group-3
light-recessed-group-4

**Comment by Mariusthvdb** [comment]
sure, I can see the images here. the thing is the icons are not displaying like that by Home Assistant, probably the paths are not correct, or some other edit in the .svg files.

I never edit them myself except for setting the fill color, so cant help you out. Maybe Andy, the author of the `[Philips Hue icon library](https://github.com/arallsopp/hass-hue-icons)` can, he is a magician with icons

**Comment by schmittyd** [comment]
I have reached out to Andy, just waiting for a response.

**Comment by arallsopp** [comment]
Pretty sure Home Assistant doesn't understand transform matrix.

I've redrawn one of the files (apologies for not getting the spacing consistent) in the commentary for hass hue icons. If you try that one and find it works, then we know what to do.

I removing transform by:
- editing the svg file in a text editor to remove the <g> and <transform> tags (this ungroups and removes the transform).
- opening the resulting svg in an image editor, and positioning each one in turn until they fit right.

Leaving this comment here, just incase anyone gets stuck with the same in the future. If it turns out I'm wrong, feel free to comment to that effect. Been a while since I played with these things. :)

**Comment by Mariusthvdb** [comment]
Hi Andy!

thanks for responding, hope you're well!

**Comment by arallsopp** [comment]
> Hi Andy!
> 
> thanks for responding, hope you're well!

All good. Work (and classic cars) keeping me busy. High Tech / Low Tech for the win. :)

**Comment by Mariusthvdb** [comment]
Ive decided to no longer add .svg icons to the JS resource, and edit that manually.

The way forward is installing the available custom_component, and simply use your .svg icons in the dedicated /config/www/custom_icons.

So I will close this.

(ofc you do still need to use correct .svg icons, as the ones above are not, like we discussed.
thanks

**Pull request closed without merging**
